#服务器端口
server:
  port: 8801

#数据源配置
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3307/community?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 1
    min-idle: 1
    max-active: 20
    test-on-borrow: true
  redis:
    ##redis 单机环境配置
    host: localhost
    port: 6379
    password:
    database: 1
    ssl: false
    ##redis 集群环境配置
    #cluster:
    #  nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003
    #  commandTimeout: 5000

#spring:
#  #排除DruidDataSourceAutoConfigure
#  autoconfigure:
#    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
#  datasource:
#    dynamic:
#      #设置默认的数据源或者数据源组,默认值即为master
#      primary: master
#      datasource:
#        master:
#          url: ${blade.datasource.demo.master.url}
#          username: ${blade.datasource.demo.master.username}
#          password: ${blade.datasource.demo.master.password}
#        slave:
#          url: ${blade.datasource.demo.slave.url}
#          username: ${blade.datasource.demo.slave.username}
#          password: ${blade.datasource.demo.slave.password}
